
        $("#one").click(function(){
            $("#five").toggle();
        });
        $("#two").click(function(){
            $("#four").toggle();
        });
        $("#three").click(function(){
            $("#seven").toggle();
        });
        $("#four").click(function(){
            $("#eight").toggle();
        });
        $("#five").click(function(){
            $("#three").toggle();
        });
        $("#six").click(function(){
            $("#two").toggle();
        });
        $("#seven").click(function(){
            $("#six").toggle();
        });
        $("#eight").click(function(){
            $("#one").toggle();
        });
        $("#b1").click(function(){
           $(".common").show(); 
        });
         $("#b1").click(function(){
           $("#one").show(); 
        });
